name: Publish NPM @next
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install 💾
        run: npm ci

      - name: Version ⬆️
        run: npm version --new-version "v0.0.0-${FULL_SHA:0:6}" --no-git-tag-version
        env:
          FULL_SHA: ${{ github.sha }}

      - name: Publish @next 🚂
        run: npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
